# coding: utf-8

"""
    Library API Spec

    This is an api for a library project that will be used in our SLO course.  # noqa: E501

    OpenAPI spec version: v0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.book_api import BookApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBookApi(unittest.TestCase):
    """BookApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.book_api.BookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_book(self):
        """Test case for create_book

        """
        pass

    def test_delete_book(self):
        """Test case for delete_book

        """
        pass

    def test_get_book(self):
        """Test case for get_book

        """
        pass

    def test_list_books(self):
        """Test case for list_books

        """
        pass

    def test_update_book(self):
        """Test case for update_book

        """
        pass


if __name__ == '__main__':
    unittest.main()
