# coding: utf-8

"""
    Library API Spec

    This is an api for a library project that will be used in our SLO course.  # noqa: E501

    OpenAPI spec version: v0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_books_response import ListBooksResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListBooksResponse(unittest.TestCase):
    """ListBooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListBooksResponse(self):
        """Test ListBooksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_books_response.ListBooksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
