# coding: utf-8

# flake8: noqa
"""
    Library API Spec

    This is an api for a library project that will be used in our SLO course.  # noqa: E501

    OpenAPI spec version: v0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.book import Book
from swagger_client.models.create_book_request import CreateBookRequest
from swagger_client.models.create_book_response import CreateBookResponse
from swagger_client.models.delete_book_response import DeleteBookResponse
from swagger_client.models.list_books_response import ListBooksResponse
